import Link from "next/link";
import { ArrowRight, BookOpen } from "lucide-react";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";

export default async function BlogPage() {
  const posts = await prisma.post.findMany({ where: { status: "PUBLISHED" }, orderBy: { publishedAt: "desc" } });
  return <main className="min-h-screen bg-[#f7f4ed] text-[#172845]"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6"><Link href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#172845] font-serif font-bold text-[#d4af37]">LK</span><strong className="font-serif">LK Corporate Consult</strong></Link><Link href="/" className="text-sm font-bold">Back to site</Link></header><section className="border-y border-[#172845]/10 bg-[#e9e2d2] px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold tracking-[.2em] text-[#9e7a16]">KNOWLEDGE CENTRE</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-tight sm:text-6xl">Practical clarity for growing Nigerian businesses.</h1><p className="mt-6 max-w-xl leading-8 text-[#566177]">Regulatory updates, CAC guidance and business resources from LK Corporate Consult.</p></div></section><section className="mx-auto max-w-7xl px-6 py-16">{posts.length ? <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{posts.map(post => <article key={post.id} className="flex min-h-72 flex-col rounded-[1.5rem] bg-white p-7 shadow-sm"><span className="w-fit rounded-full bg-[#e9e2d2] px-3 py-1 text-[10px] font-bold tracking-wider text-[#80620f]">{post.category}</span><h2 className="mt-6 font-serif text-3xl leading-snug">{post.title}</h2><p className="mt-4 text-sm leading-6 text-[#566177]">{post.excerpt}</p><Link className="mt-auto inline-flex items-center gap-2 pt-7 text-sm font-bold" href={`/blog/${post.slug}`}>Read article <ArrowRight className="size-4" /></Link></article>)}</div> : <div className="grid min-h-72 place-items-center rounded-[1.5rem] border border-dashed border-[#172845]/20 text-center"><div><BookOpen className="mx-auto size-8 text-[#b38b18]" /><h2 className="mt-4 font-serif text-3xl">Insights are on their way.</h2><p className="mt-2 text-[#566177]">Check back soon for clear, actionable business guidance.</p></div></div>}</section></main>;
}
