"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Save, Send } from "lucide-react";
type Post = { id?: string; title?: string; slug?: string; excerpt?: string; content?: string; category?: string };
export function ArticleEditor({ post }: { post?: Post }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save(form: HTMLFormElement, status: string) { setBusy(true); setError(""); const data = { ...Object.fromEntries(new FormData(form)), status }; const response = await fetch(post?.id ? `/api/admin/posts/${post.id}` : "/api/admin/posts", { method: post?.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); setBusy(false); if (!response.ok) return setError((await response.json()).error || "Could not save this article."); router.push("/admin"); router.refresh(); }
  async function remove() { if (!post?.id || !confirm("Delete this article permanently?")) return; setBusy(true); await fetch(`/api/admin/posts/${post.id}`, { method: "DELETE" }); router.push("/admin"); router.refresh(); }
  return <main className="min-h-screen bg-[#f1eee6] p-5 sm:p-8"><form onSubmit={(e) => { e.preventDefault(); save(e.currentTarget, "DRAFT"); }} className="mx-auto max-w-4xl"><button type="button" onClick={() => router.push("/admin")} className="inline-flex items-center gap-2 text-sm font-bold text-[#172845]"><ArrowLeft className="size-4" /> Dashboard</button><div className="mt-7 rounded-[1.75rem] bg-white p-6 sm:p-9"><p className="text-xs font-bold tracking-[.18em] text-[#9e7a16]">EDITORIAL WORKSPACE</p><h1 className="mt-2 font-serif text-4xl text-[#172845]">{post ? "Refine article" : "Create a new insight"}</h1><div className="mt-9 grid gap-5"><label className="text-sm font-bold">Article title<input required name="title" defaultValue={post?.title} className="mt-2 w-full rounded-xl border border-[#172845]/15 px-4 py-3 font-normal outline-none focus:border-[#d4af37]" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Category<input required name="category" defaultValue={post?.category} placeholder="e.g. CAC Compliance" className="mt-2 w-full rounded-xl border border-[#172845]/15 px-4 py-3 font-normal outline-none focus:border-[#d4af37]" /></label><label className="text-sm font-bold">URL slug <span className="font-normal text-[#68748a]">(optional for new posts)</span><input name="slug" defaultValue={post?.slug} className="mt-2 w-full rounded-xl border border-[#172845]/15 px-4 py-3 font-normal outline-none focus:border-[#d4af37]" /></label></div><label className="text-sm font-bold">Short excerpt<textarea required name="excerpt" defaultValue={post?.excerpt} rows={3} className="mt-2 w-full rounded-xl border border-[#172845]/15 px-4 py-3 font-normal outline-none focus:border-[#d4af37]" /></label><label className="text-sm font-bold">Article body<textarea required name="content" defaultValue={post?.content} rows={16} className="mt-2 w-full rounded-xl border border-[#172845]/15 px-4 py-3 font-normal leading-7 outline-none focus:border-[#d4af37]" /></label></div>{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-8 flex flex-wrap gap-3"><button disabled={busy} className="inline-flex items-center gap-2 rounded-full border border-[#172845]/20 px-5 py-3 font-bold disabled:opacity-60"><Save className="size-4" /> Save draft</button><button type="button" disabled={busy} onClick={(e) => save(e.currentTarget.form!, "PUBLISHED")} className="inline-flex items-center gap-2 rounded-full bg-[#d4af37] px-5 py-3 font-bold disabled:opacity-60"><Send className="size-4" /> Publish article</button>{post && <button type="button" disabled={busy} onClick={remove} className="ml-auto px-4 py-3 text-sm font-bold text-red-700">Delete article</button>}</div></div></form></main>;
}
